### PR TITLE
Dynamic Guarantee Period Paretix

### PR DESCRIPTION
**Pull request by razprod**
Calculated guarantee periods using start date and end date - Paretix

### CODE REVIEW

**Comment by razprod** [comment]
@manikant0018 Is this branch logic up to date?
Do we need the code inside?
- There're conflicts which can be fixed but generally speaking about that branch.

**Comment by manikant0018** [comment]
Let me check please. let you know once I confirmed.

**Comment by razprod** [comment]
> Let me check please. let you know once I confirmed.

Ok, awesome

**Comment by manikant0018** [comment]
Yes tasks is done here already. I checked all files

**Comment by razprod** [comment]
> Yes tasks is done here already. I checked all files

Is it already done on Development branch? Or are you mean that this branch is good for merge?

**Comment by manikant0018** [comment]
I mean branch is good for the merge. No idea about is done on dev

**Comment by razprod** [comment]
> I mean branch is good for the merge. No idea about is done on dev

Ok, then I'll handle the merge conflict.

**Pull request merged**
